name: Open a GitHub Issue
author: '@DanielSCrouch'
description: Opens a GitHub Issue
inputs:
  token:
    description: GitHub authentication token
    required: true
  title:
    description: Issue title
    required: true
  body:
    description: Issue body
  assignees:
    description: Issue assignees
outputs:
  issue:
    description: 'The issue object as a json string'
runs:
  using: 'node12'
  main: 'dist/index.js'
