---
apiVersion: v1
kind: Namespace
metadata:
  name: actions
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: actions
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      terminationGracePeriodSeconds: 1
      imagePullSecrets:
        - name: docker-secret
      tolerations:
        - key: 'node-role.kubernetes.io/master'
          operator: 'Exists'
          effect: 'NoSchedule'
        - key: 'node-role.kubernetes.io/control-plane'
          operator: 'Exists'
          effect: 'NoSchedule'
      containers:
        - name: app
          image: docker.io/duartcs/app:dev
          imagePullPolicy: Always
          ports:
            - name: api-server
              protocol: TCP
              containerPort: 30000
          env:
            - name: HOST_ADDR
              value: '0.0.0.0'
            - name: HOST_PORT
              value: '30000'
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: actions
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - name: api-server
      protocol: TCP
      port: 30000
      nodePort: 30000
      targetPort: api-server
# curl http://app-svc.actions.svc.cluster.local
